# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f4296cdf1301c9871850e2c2887bcd27c5dee3edad84979bf04eb91160059efefa58aaa93bf4e4ad751b018006d61476c4ad7b91850f170cc2ea52e5f0b5204

test:
  secret_key_base: da7cb4a162370e077a8b9b09e762311a4b5291737aa0560bdaa635e1f3d91577e22ef76adce46ba6b1075f73b3c28e118d291d0f1b0d46152b3c469309c38e74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
